### ISSUE TITLE
Add checker script (later custom github action)

### ISSUE THREAD

**Issue by christianparpart** [frequenz-floss/flake8-numbers#1]
### What's needed?

Make sure ~we don't have quantities with a lot of trailing zeros~, and that large numbers use `_` as separator, ~and use the `.zero()` constructor instead of `.from_xxx(0).`~.

- [x] validate numeric literals to be well formatted with `_` if needed
- [ ] ~validate bad use of `QUANTITY.from_xxx(0)` to use `QUANTITY.zero()` instead~
- [ ] ~validate we don't have quantities with a lot of trailing zeros and use an appropriate `from_xxx()` instead~

### Proposed solution

checker script to be invoked, or eventually even an SDK github action that can be easily used to check Frequenz / SDK related QA topics

- the script should be easily implementable
- a github action is the long-term preferred way: see [here](https://docs.github.com/en/actions/creating-actions) on how to implement

### Use cases

All of our own code, Frequenz SDK as well as our actors, but ultimatively also for external users, making use of the Frequenz SDK and its actors.

### Alternatives and workarounds

manual code review

**Comment by llucax** [comment]
I updated the description of this issue to strike out stuff that is out of the scope of this repo. The basic functionality is already implemented, so closing.
