### ISSUE TITLE
Configure the GitHub repository

### ISSUE THREAD

**Issue by llucax** [frequenz-floss/flake8-numbers#8]
### What's needed?

The repository should have branch protection rules, etc.

### Proposed solution

Follow the steps in:

* https://github.com/frequenz-floss/frequenz-repo-config-python/wiki/Configuring-a-new-GitHub-repository

**Comment by christianparpart** [comment]
applied.

the only thing left out AFAICT is that I do not forbid creating branches in this repo (the whildcard rule), purposely.

**Comment by llucax** [comment]
May I ask why? I'm fine with it as it is a small project, but I'm curious.

**Comment by llucax** [comment]
BTW, I just also added these checks as requirements for merging:

![image](https://github.com/frequenz-floss/flake8-numbers/assets/1031485/a5fdaee9-7ca1-4128-991c-119575a4c525)
